require('dotenv').config();
const http=require('http'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const nodemailer=require('nodemailer');
const {Pool}=require('pg');
const PORT=Number(process.env.PORT||3000),ROOT=__dirname,PUB=path.join(ROOT,'public'),DB=process.env.DATABASE_URL,SESSION_HOURS=12;
const PUBLIC_HOST=String(process.env.PUBLIC_HOST||'').toLowerCase().replace(/^https?:\/\//,'').replace(/\/$/,'');
const CONTROL_HOST=String(process.env.CONTROL_HOST||'').toLowerCase().replace(/^https?:\/\//,'').replace(/\/$/,'');
function requestHost(req){return String(req.headers['x-forwarded-host']||req.headers.host||'').split(',')[0].trim().toLowerCase().split(':')[0]}
function hostMode(req){return 'control'}
if(!DB){console.error('DATABASE_URL tanımlı değil');process.exit(1)}
const internal=/railway\.internal/i.test(DB);const ssl=process.env.DATABASE_SSL==='true'||(process.env.DATABASE_SSL!=='false'&&!internal&&process.env.NODE_ENV==='production');
const pool=new Pool({connectionString:DB,ssl:ssl?{rejectUnauthorized:false}:false,max:10,connectionTimeoutMillis:10000});let databaseReady=false,databaseError=null;
const resetAttempts=new Map();
function clientIp(req){return String(req.headers['x-forwarded-for']||req.socket.remoteAddress||'unknown').split(',')[0].trim()}
function resetRateAllowed(req){const key=clientIp(req),now=Date.now(),windowMs=15*60*1000,max=5;let list=(resetAttempts.get(key)||[]).filter(t=>now-t<windowMs);if(list.length>=max){resetAttempts.set(key,list);return false}list.push(now);resetAttempts.set(key,list);return true}
setInterval(()=>{const now=Date.now();for(const [k,v] of resetAttempts){const n=v.filter(t=>now-t<15*60*1000);if(n.length)resetAttempts.set(k,n);else resetAttempts.delete(k)}},10*60*1000).unref();
const clean=(v,m=500)=>String(v||'').trim().slice(0,m),slugify=v=>clean(v,80).toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/ı/g,'i').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
const validDate=v=>/^\d{4}-\d{2}-\d{2}$/.test(v),validTime=v=>/^([01]\d|2[0-3]):[0-5]\d$/.test(v);
function hash(p,s){return crypto.scryptSync(p,s,64).toString('hex')}
const tokenHash=t=>crypto.createHash('sha256').update(String(t)).digest('hex');
function publicBaseUrl(req){const configured=clean(process.env.APP_URL||'https://control.atabari.live',500).replace(/\/$/,'');if(configured)return configured;const proto=req.headers['x-forwarded-proto']||'http';return `${proto}://${req.headers.host}`;}
function mailTransport(){if(!process.env.SMTP_HOST||!process.env.SMTP_USER||!process.env.SMTP_PASS)return null;return nodemailer.createTransport({host:process.env.SMTP_HOST,port:Number(process.env.SMTP_PORT||587),secure:String(process.env.SMTP_SECURE||'false')==='true',auth:{user:process.env.SMTP_USER,pass:process.env.SMTP_PASS},tls:{rejectUnauthorized:String(process.env.SMTP_TLS_REJECT_UNAUTHORIZED||'true')!=='false'}})}
function emailFrame(title,content){return `<div style="background:#0b0b0d;padding:32px 12px;font-family:Arial,sans-serif;color:#fff"><div style="max-width:580px;margin:auto;background:#151518;border:1px solid #2b2b31;border-radius:18px;overflow:hidden"><div style="padding:22px 26px;border-bottom:3px solid #e52b24"><div style="font-size:13px;color:#aaa;letter-spacing:2px">ATABARI CONTROL CENTER</div><h2 style="margin:8px 0 0;color:#fff">${title}</h2></div><div style="padding:26px;line-height:1.65">${content}</div><div style="padding:18px 26px;background:#101012;color:#777;font-size:12px">Bu e-posta ATABARI Control Center tarafından otomatik gönderilmiştir.</div></div></div>`}
async function sendMail({to,subject,text,html}){const tr=mailTransport();if(!tr)throw new Error('E-posta servisi yapılandırılmadı.');return tr.sendMail({from:process.env.EMAIL_FROM||process.env.SMTP_USER,to,subject,text,html})}
async function sendResetEmail(to,link){await sendMail({to,subject:'ATABARI - Şifre sıfırlama bağlantısı',text:`Şifrenizi sıfırlamak için bağlantıyı açın: ${link}\n\nBağlantı 30 dakika geçerlidir ve yalnızca bir kez kullanılabilir.`,html:emailFrame('Şifre Sıfırlama Talebi',`<p>Hesabınızın şifresini yenilemek için aşağıdaki butona tıklayın.</p><p style="margin:26px 0"><a href="${link}" style="display:inline-block;padding:13px 20px;background:#e52b24;color:#fff;text-decoration:none;border-radius:10px;font-weight:700">Şifremi Sıfırla</a></p><p style="color:#aaa">Bu bağlantı <b>30 dakika</b> geçerlidir ve yalnızca bir kez kullanılabilir.</p><p style="color:#777;font-size:13px">Bu talebi siz oluşturmadıysanız e-postayı yok sayabilirsiniz.</p>`)})}
async function sendPasswordChangedEmail(to,when){if(!to)return;await sendMail({to,subject:'ATABARI - Şifreniz değiştirildi',text:`Hesabınızın şifresi ${when} tarihinde değiştirildi. Bu işlemi siz yapmadıysanız yöneticinizle hemen iletişime geçin.`,html:emailFrame('Şifre Değişikliği Bildirimi',`<p>Hesabınızın şifresi <b>${when}</b> tarihinde değiştirildi.</p><p>Bu işlemi siz yapmadıysanız yöneticinizle hemen iletişime geçin.</p>`)})}
async function sendTestEmail(to){await sendMail({to,subject:'ATABARI - SMTP test e-postası',text:'SMTP ayarlarınız başarıyla çalışıyor.',html:emailFrame('E-posta Sistemi Çalışıyor',`<p>Bu test mesajını görüyorsanız Natro/SMTP bağlantınız başarıyla yapılandırılmıştır.</p><p style="color:#aaa">Artık şifre sıfırlama ve güvenlik bildirimleri otomatik gönderilebilir.</p>`)})}
async function sendSponsorReminderEmail(to,r){if(!to)return;const list=Array.isArray(r.checklist)?r.checklist:[];await sendMail({to,subject:`Sponsor hatırlatması: ${r.brand_name}`,text:`${r.brand_name} - ${r.title}\n\n${r.message||''}\nKod: ${r.promo_code||'-'}\nLink: ${r.promo_link||'-'}`,html:emailFrame('Sponsor Hatırlatması',`<p><b>${r.brand_name}</b> · ${r.title}</p><p>${r.message||'Sponsor görev zamanı geldi.'}</p>${r.promo_code?`<p><b>Kod:</b> ${r.promo_code}</p>`:''}${r.promo_link?`<p><a href="${r.promo_link}" style="color:#ff6158">Sponsor bağlantısını aç</a></p>`:''}${list.length?`<ul>${list.map(x=>`<li>${x}</li>`).join('')}</ul>`:''}`)})}
function json(res,c,o,h={}){res.writeHead(c,{'Content-Type':'application/json; charset=utf-8',...h});res.end(JSON.stringify(o))}
function body(req){return new Promise((ok,no)=>{let d='';req.on('data',c=>{d+=c;if(d.length>500000){no(new Error('İstek çok büyük'));req.destroy()}});req.on('end',()=>{try{ok(d?JSON.parse(d):{})}catch(e){no(e)}})})}
function cookies(req){return Object.fromEntries((req.headers.cookie||'').split(';').filter(Boolean).map(x=>{let i=x.indexOf('=');return[x.slice(0,i).trim(),decodeURIComponent(x.slice(i+1))]}))}
function serve(res,file){if(!fs.existsSync(file)){res.writeHead(404);return res.end('Not found')}const ext=path.extname(file),types={'.html':'text/html; charset=utf-8','.css':'text/css; charset=utf-8','.js':'application/javascript; charset=utf-8','.png':'image/png','.svg':'image/svg+xml','.ico':'image/x-icon'};res.writeHead(200,{'Content-Type':types[ext]||'application/octet-stream','X-Content-Type-Options':'nosniff'});fs.createReadStream(file).pipe(res)}
async function migrate(){await pool.query(`
CREATE TABLE IF NOT EXISTS streamers(id BIGSERIAL PRIMARY KEY,slug VARCHAR(90) UNIQUE NOT NULL,display_name VARCHAR(100) NOT NULL,kick_username VARCHAR(100) NOT NULL DEFAULT '',kick_url VARCHAR(300) NOT NULL DEFAULT '',avatar_url VARCHAR(500) NOT NULL DEFAULT '',bio TEXT NOT NULL DEFAULT '',categories VARCHAR(300) NOT NULL DEFAULT '',socials JSONB NOT NULL DEFAULT '{}'::jsonb,active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS users(id BIGSERIAL PRIMARY KEY,username VARCHAR(60) UNIQUE NOT NULL,salt VARCHAR(64) NOT NULL,password_hash VARCHAR(256) NOT NULL,role VARCHAR(30) NOT NULL DEFAULT 'admin',streamer_id BIGINT REFERENCES streamers(id) ON DELETE SET NULL,active BOOLEAN NOT NULL DEFAULT TRUE,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
ALTER TABLE users ADD COLUMN IF NOT EXISTS streamer_id BIGINT REFERENCES streamers(id) ON DELETE SET NULL;ALTER TABLE users ADD COLUMN IF NOT EXISTS active BOOLEAN NOT NULL DEFAULT TRUE;ALTER TABLE users ADD COLUMN IF NOT EXISTS email VARCHAR(254);ALTER TABLE users ADD COLUMN IF NOT EXISTS last_password_changed_at TIMESTAMPTZ;
CREATE TABLE IF NOT EXISTS broadcasts(id BIGSERIAL PRIMARY KEY,streamer VARCHAR(100) NOT NULL,streamer_id BIGINT REFERENCES streamers(id) ON DELETE SET NULL,title VARCHAR(120) NOT NULL,broadcast_date DATE NOT NULL,start_time TIME NOT NULL,end_time TIME NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'planned',url VARCHAR(300) NOT NULL DEFAULT '',description TEXT NOT NULL DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),CHECK(end_time>start_time));
ALTER TABLE broadcasts ADD COLUMN IF NOT EXISTS streamer_id BIGINT REFERENCES streamers(id) ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS broadcasts_date_time_idx ON broadcasts(broadcast_date,start_time,end_time);
CREATE TABLE IF NOT EXISTS settings(key VARCHAR(80) PRIMARY KEY,value JSONB NOT NULL,updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS sessions(id VARCHAR(96) PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,expires_at TIMESTAMPTZ NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS password_reset_tokens(id BIGSERIAL PRIMARY KEY,user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,token_hash VARCHAR(64) UNIQUE NOT NULL,expires_at TIMESTAMPTZ NOT NULL,used_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX IF NOT EXISTS password_reset_user_idx ON password_reset_tokens(user_id,created_at DESC);
CREATE TABLE IF NOT EXISTS email_logs(id BIGSERIAL PRIMARY KEY,user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,recipient VARCHAR(254) NOT NULL,email_type VARCHAR(50) NOT NULL,status VARCHAR(20) NOT NULL,error_message TEXT NOT NULL DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS moderator_reports(id BIGSERIAL PRIMARY KEY,broadcast_id BIGINT NOT NULL REFERENCES broadcasts(id) ON DELETE CASCADE,moderator_user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,attendance_status VARCHAR(30) NOT NULL DEFAULT 'ok',actual_start TIME,actual_end TIME,technical_issue TEXT NOT NULL DEFAULT '',note TEXT NOT NULL DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX IF NOT EXISTS reports_broadcast_idx ON moderator_reports(broadcast_id);
CREATE TABLE IF NOT EXISTS announcements(id BIGSERIAL PRIMARY KEY,title VARCHAR(140) NOT NULL,content TEXT NOT NULL DEFAULT '',priority VARCHAR(20) NOT NULL DEFAULT 'normal',active BOOLEAN NOT NULL DEFAULT TRUE,created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS sponsors(id BIGSERIAL PRIMARY KEY,brand_name VARCHAR(140) NOT NULL,campaign_name VARCHAR(180) NOT NULL DEFAULT '',logo_url VARCHAR(500) NOT NULL DEFAULT '',start_date DATE,end_date DATE,status VARCHAR(20) NOT NULL DEFAULT 'active',brief TEXT NOT NULL DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS sponsor_tasks(id BIGSERIAL PRIMARY KEY,sponsor_id BIGINT NOT NULL REFERENCES sponsors(id) ON DELETE CASCADE,broadcast_id BIGINT REFERENCES broadcasts(id) ON DELETE SET NULL,streamer_id BIGINT REFERENCES streamers(id) ON DELETE SET NULL,task_type VARCHAR(60) NOT NULL,title VARCHAR(180) NOT NULL,due_at TIMESTAMPTZ,status VARCHAR(20) NOT NULL DEFAULT 'pending',proof_url VARCHAR(500) NOT NULL DEFAULT '',note TEXT NOT NULL DEFAULT '',created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS sponsor_reminders(id BIGSERIAL PRIMARY KEY,sponsor_task_id BIGINT NOT NULL REFERENCES sponsor_tasks(id) ON DELETE CASCADE,broadcast_id BIGINT NOT NULL REFERENCES broadcasts(id) ON DELETE CASCADE,streamer_id BIGINT NOT NULL REFERENCES streamers(id) ON DELETE CASCADE,created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,timing_mode VARCHAR(30) NOT NULL DEFAULT 'after_start',offset_minutes INTEGER NOT NULL DEFAULT 30,absolute_at TIMESTAMPTZ,message TEXT NOT NULL DEFAULT '',promo_code VARCHAR(140) NOT NULL DEFAULT '',promo_link VARCHAR(500) NOT NULL DEFAULT '',checklist JSONB NOT NULL DEFAULT '[]'::jsonb,status VARCHAR(30) NOT NULL DEFAULT 'pending',remind_at TIMESTAMPTZ NOT NULL,notified_at TIMESTAMPTZ,seen_at TIMESTAMPTZ,completed_at TIMESTAMPTZ,snoozed_until TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX IF NOT EXISTS sponsor_reminders_due_idx ON sponsor_reminders(status,remind_at);
CREATE INDEX IF NOT EXISTS sponsor_tasks_due_idx ON sponsor_tasks(due_at,status);
CREATE TABLE IF NOT EXISTS operation_notes(id BIGSERIAL PRIMARY KEY,broadcast_id BIGINT REFERENCES broadcasts(id) ON DELETE CASCADE,user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,note_type VARCHAR(30) NOT NULL DEFAULT 'note',content TEXT NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS daily_tasks(id BIGSERIAL PRIMARY KEY,title VARCHAR(180) NOT NULL,description TEXT NOT NULL DEFAULT '',task_date DATE NOT NULL DEFAULT CURRENT_DATE,assigned_user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,assigned_streamer_id BIGINT REFERENCES streamers(id) ON DELETE SET NULL,broadcast_id BIGINT REFERENCES broadcasts(id) ON DELETE SET NULL,priority VARCHAR(20) NOT NULL DEFAULT 'normal',status VARCHAR(20) NOT NULL DEFAULT 'pending',created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,completed_at TIMESTAMPTZ,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX IF NOT EXISTS daily_tasks_date_idx ON daily_tasks(task_date,status);
CREATE TABLE IF NOT EXISTS broadcast_briefings(id BIGSERIAL PRIMARY KEY,broadcast_id BIGINT UNIQUE NOT NULL REFERENCES broadcasts(id) ON DELETE CASCADE,talking_points TEXT NOT NULL DEFAULT '',restricted_topics TEXT NOT NULL DEFAULT '',sponsor_code VARCHAR(120) NOT NULL DEFAULT '',important_links TEXT NOT NULL DEFAULT '',special_notes TEXT NOT NULL DEFAULT '',updated_by BIGINT REFERENCES users(id) ON DELETE SET NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE TABLE IF NOT EXISTS score_events(id BIGSERIAL PRIMARY KEY,user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,streamer_id BIGINT REFERENCES streamers(id) ON DELETE CASCADE,broadcast_id BIGINT REFERENCES broadcasts(id) ON DELETE SET NULL,points INTEGER NOT NULL,reason VARCHAR(220) NOT NULL,created_by BIGINT REFERENCES users(id) ON DELETE SET NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),CHECK(user_id IS NOT NULL OR streamer_id IS NOT NULL));
CREATE INDEX IF NOT EXISTS score_events_created_idx ON score_events(created_at DESC);

ALTER TABLE users ADD COLUMN IF NOT EXISTS display_name VARCHAR(120) NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS bio TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS avatar_url TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS cover_url TEXT NOT NULL DEFAULT '';
ALTER TABLE users ADD COLUMN IF NOT EXISTS theme VARCHAR(30) NOT NULL DEFAULT 'midnight';
ALTER TABLE users ADD COLUMN IF NOT EXISTS accent VARCHAR(30) NOT NULL DEFAULT 'red';
ALTER TABLE users ADD COLUMN IF NOT EXISTS density VARCHAR(20) NOT NULL DEFAULT 'comfortable';
ALTER TABLE users ADD COLUMN IF NOT EXISTS reduce_motion BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE users ADD COLUMN IF NOT EXISTS font_scale VARCHAR(20) NOT NULL DEFAULT 'normal';
ALTER TABLE users ADD COLUMN IF NOT EXISTS high_contrast BOOLEAN NOT NULL DEFAULT FALSE;
CREATE TABLE IF NOT EXISTS activity_logs(id BIGSERIAL PRIMARY KEY,user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,action VARCHAR(100) NOT NULL,entity_type VARCHAR(60) NOT NULL DEFAULT '',entity_id BIGINT,detail JSONB NOT NULL DEFAULT '{}'::jsonb,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW());
CREATE INDEX IF NOT EXISTS activity_logs_created_idx ON activity_logs(created_at DESC);
`);await pool.query("INSERT INTO settings(key,value) VALUES('site',$1::jsonb) ON CONFLICT(key) DO NOTHING",[JSON.stringify({teamName:'ATABARI Control Center',timezone:'Europe/Istanbul'})]);await pool.query('DELETE FROM sessions WHERE expires_at<NOW()')}
async function getUser(req){let sid=cookies(req).sid;if(!sid)return null;let r=await pool.query(`SELECT u.id,u.username,u.email,u.role,u.streamer_id,u.active,u.display_name,u.avatar_url,u.theme,u.accent,u.density,u.reduce_motion,u.font_scale,u.high_contrast FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.id=$1 AND s.expires_at>NOW() AND u.active=TRUE`,[sid]);return r.rows[0]||null}
async function auth(req,res,roles=[]){let u=await getUser(req);if(!u){json(res,401,{error:'Oturum gerekli.'});return null}if(roles.length&&!roles.includes(u.role)){json(res,403,{error:'Bu işlem için yetkiniz yok.'});return null}return u}
function mapStreamer(r){return{id:Number(r.id),slug:r.slug,name:r.display_name,kickUsername:r.kick_username,kickUrl:r.kick_url,avatarUrl:r.avatar_url,bio:r.bio,categories:r.categories,socials:r.socials||{},active:r.active}}
function mapBroadcast(r){return{id:Number(r.id),streamer:r.streamer,streamerId:r.streamer_id?Number(r.streamer_id):null,streamerSlug:r.streamer_slug||null,avatarUrl:r.avatar_url||'',title:r.title,date:String(r.broadcast_date).slice(0,10),start:String(r.start_time).slice(0,5),end:String(r.end_time).slice(0,5),status:r.status,url:r.url,description:r.description}}
const broadcastSelect=`SELECT b.*,s.slug streamer_slug,s.avatar_url FROM broadcasts b LEFT JOIN streamers s ON s.id=b.streamer_id`;
async function publicData(){let[b,s,set]=await Promise.all([pool.query(`${broadcastSelect} ORDER BY b.broadcast_date,b.start_time`),pool.query('SELECT * FROM streamers WHERE active=TRUE ORDER BY display_name'),pool.query("SELECT value FROM settings WHERE key='site'")]);return{broadcasts:b.rows.map(mapBroadcast),streamers:s.rows.map(mapStreamer),settings:set.rows[0]?.value||{teamName:'ATABARI Control Center'}}}
function broadcastInput(i){return{streamerId:Number(i.streamerId)||null,streamer:clean(i.streamer,100),title:clean(i.title,120),date:clean(i.date,10),start:clean(i.start,5),end:clean(i.end,5),status:['planned','live','done','cancelled'].includes(i.status)?i.status:'planned',url:clean(i.url,300),description:clean(i.description,1200)}}
async function conflict(c,x,id=null){let v=[x.date,x.start,x.end],q=`SELECT 1 FROM broadcasts WHERE broadcast_date=$1::date AND status<>'cancelled' AND start_time<$3::time AND end_time>$2::time`;if(id){v.push(id);q+=' AND id<>$4'}return(await c.query(q+' LIMIT 1',v)).rowCount>0}
const server=http.createServer(async(req,res)=>{try{let u=new URL(req.url,'http://localhost'),p=u.pathname,mode=hostMode(req);res.setHeader('X-Frame-Options','SAMEORIGIN');res.setHeader('Referrer-Policy','same-origin');res.setHeader('X-Content-Type-Options','nosniff');res.setHeader('Permissions-Policy','camera=(), microphone=(), geolocation=()');if(mode==='control'){res.setHeader('X-Robots-Tag','noindex, nofollow, noarchive');res.setHeader('Cache-Control','no-store')}
if(p==='/robots.txt')return serve(res,path.join(PUB,mode==='control'?'robots-control.txt':'robots-public.txt'));
// Public alan adında yönetim uçları ve panel dosyaları hiçbir zaman sunulmaz.
if(mode==='public'){
  const publicApi=p==='/api/health'||p==='/api/public'||p.startsWith('/api/public/');
  const publicPage=p==='/'||p==='/index.html'||p==='/yayincilar'||p==='/yayincilar/'||/^\/yayinci\/[a-z0-9-]+\/?$/.test(p)||['/app.css','/logo.png','/robots.txt'].includes(p);
  if(p.startsWith('/api/')&&!publicApi)return json(res,404,{error:'Bulunamadı.'});
  if(!p.startsWith('/api/')&&!publicPage){res.writeHead(404,{'Content-Type':'text/html; charset=utf-8'});return res.end('<!doctype html><meta charset="utf-8"><title>Bulunamadı</title><h1>Sayfa bulunamadı</h1>')}
}
// Control alan adı yalnızca ekip panelini ve kimlik doğrulama akışlarını sunar.
if(mode==='control'&&['/yayincilar','/yayincilar/'].includes(p))return json(res,404,{error:'Bulunamadı.'});
if(req.method==='GET'&&p==='/api/health')return json(res,200,{ok:true,database:databaseReady?'ready':'connecting'});if(p.startsWith('/api/')&&!databaseReady)return json(res,503,{error:'Veritabanı hazırlanıyor.',detail:process.env.NODE_ENV==='production'?undefined:databaseError?.message});
if(req.method==='GET'&&p==='/api/public')return json(res,200,await publicData());
let pm=p.match(/^\/api\/public\/streamers\/([a-z0-9-]+)$/);if(req.method==='GET'&&pm){let st=await pool.query('SELECT * FROM streamers WHERE slug=$1 AND active=TRUE',[pm[1]]);if(!st.rowCount)return json(res,404,{error:'Yayıncı bulunamadı.'});let br=await pool.query(`${broadcastSelect} WHERE b.streamer_id=$1 ORDER BY b.broadcast_date DESC,b.start_time DESC`,[st.rows[0].id]);return json(res,200,{streamer:mapStreamer(st.rows[0]),broadcasts:br.rows.map(mapBroadcast)})}
if(req.method==='GET'&&p==='/api/setup/status'){let r=await pool.query("SELECT COUNT(*)::int AS count FROM users WHERE role='owner' AND active=TRUE");return json(res,200,{setupRequired:r.rows[0].count===0})}
if(req.method==='POST'&&p==='/api/setup'){let count=await pool.query("SELECT COUNT(*)::int AS count FROM users WHERE role='owner' AND active=TRUE");if(count.rows[0].count>0)return json(res,409,{error:'Kurulum daha önce tamamlanmış.'});let i=await body(req),displayName=clean(i.displayName,120),username=clean(i.username,60).toLowerCase(),email=clean(i.email,254).toLowerCase(),pass=String(i.password||''),confirm=String(i.passwordConfirm||'');if(!displayName||!username||!email)return json(res,400,{error:'Ad soyad, kullanıcı adı ve e-posta zorunludur.'});if(!/^[a-z0-9._-]{3,60}$/.test(username))return json(res,400,{error:'Kullanıcı adı en az 3 karakter olmalı; yalnızca harf, rakam, nokta, alt çizgi ve tire kullanılabilir.'});if(!/^\S+@\S+\.\S+$/.test(email))return json(res,400,{error:'Geçerli bir e-posta adresi girin.'});if(pass!==confirm)return json(res,400,{error:'Şifreler eşleşmiyor.'});if(pass.length<12||!/[A-Z]/.test(pass)||!/[a-z]/.test(pass)||!/[0-9]/.test(pass)||!/[!@#$%^&*()_+\-=\[\]{};':"\|,.<>/?]/.test(pass))return json(res,400,{error:'Şifre en az 12 karakter olmalı ve büyük harf, küçük harf, rakam ve özel karakter içermelidir.'});let c=await pool.connect();try{await c.query('BEGIN');await c.query('SELECT pg_advisory_xact_lock(891337)');let again=await c.query("SELECT COUNT(*)::int AS count FROM users WHERE role='owner' AND active=TRUE");if(again.rows[0].count>0){await c.query('ROLLBACK');return json(res,409,{error:'Kurulum başka bir oturumda tamamlandı.'})}let salt=crypto.randomBytes(16).toString('hex');let r=await c.query(`INSERT INTO users(username,email,display_name,salt,password_hash,role,active,last_password_changed_at) VALUES($1,$2,$3,$4,$5,'owner',TRUE,NOW()) RETURNING id,username,email,display_name,role`,[username,email,displayName,salt,hash(pass,salt)]);let sid=crypto.randomBytes(36).toString('hex');await c.query(`INSERT INTO sessions(id,user_id,expires_at) VALUES($1,$2,NOW()+($3||' hours')::interval)`,[sid,r.rows[0].id,String(SESSION_HOURS)]);await c.query(`INSERT INTO activity_logs(user_id,action,entity_type,entity_id,detail) VALUES($1,'owner_setup_completed','user',$1,$2::jsonb)`,[r.rows[0].id,JSON.stringify({username,email})]);await c.query('COMMIT');return json(res,201,{ok:true,user:r.rows[0]},{'Set-Cookie':`sid=${sid}; HttpOnly; SameSite=Lax; Path=/; Max-Age=${SESSION_HOURS*3600}${process.env.NODE_ENV==='production'?'; Secure':''}`})}catch(e){await c.query('ROLLBACK');if(e.code==='23505')return json(res,409,{error:'Bu kullanıcı adı veya e-posta zaten kullanılıyor.'});throw e}finally{c.release()}}
if(req.method==='GET'&&p==='/api/session')return json(res,200,{user:await getUser(req)});
if(req.method==='POST'&&p==='/api/login'){let i=await body(req),r=await pool.query('SELECT * FROM users WHERE username=$1 AND active=TRUE',[clean(i.username,60)]),f=r.rows[0];if(!f||hash(String(i.password||''),f.salt)!==f.password_hash)return json(res,401,{error:'Kullanıcı adı veya şifre hatalı.'});let sid=crypto.randomBytes(36).toString('hex');await pool.query(`INSERT INTO sessions(id,user_id,expires_at) VALUES($1,$2,NOW()+($3||' hours')::interval)`,[sid,f.id,String(SESSION_HOURS)]);return json(res,200,{user:{id:Number(f.id),username:f.username,displayName:f.display_name||f.username,avatarUrl:f.avatar_url||'',role:f.role,streamerId:f.streamer_id?Number(f.streamer_id):null,theme:f.theme||'midnight'}},{'Set-Cookie':`sid=${sid}; HttpOnly; SameSite=Lax; Path=/; Max-Age=${SESSION_HOURS*3600}${process.env.NODE_ENV==='production'?'; Secure':''}`})}
if(req.method==='POST'&&p==='/api/forgot-password'){if(!resetRateAllowed(req))return json(res,429,{error:'Çok fazla deneme yapıldı. 15 dakika sonra tekrar deneyin.'});let i=await body(req),email=clean(i.email,254).toLowerCase();const generic={ok:true,message:'Bu e-posta kayıtlıysa sıfırlama bağlantısı gönderildi.'};if(!email)return json(res,200,generic);let r=await pool.query('SELECT id,email FROM users WHERE LOWER(email)=LOWER($1) AND active=TRUE LIMIT 1',[email]),f=r.rows[0];if(!f)return json(res,200,generic);let recent=await pool.query("SELECT 1 FROM password_reset_tokens WHERE user_id=$1 AND created_at>NOW()-INTERVAL '2 minutes' LIMIT 1",[f.id]);if(recent.rowCount)return json(res,200,generic);let token=crypto.randomBytes(32).toString('hex');await pool.query('UPDATE password_reset_tokens SET used_at=NOW() WHERE user_id=$1 AND used_at IS NULL',[f.id]);await pool.query("INSERT INTO password_reset_tokens(user_id,token_hash,expires_at) VALUES($1,$2,NOW()+INTERVAL '30 minutes')",[f.id,tokenHash(token)]);let link=`${publicBaseUrl(req)}/reset-password?token=${encodeURIComponent(token)}`;try{await sendResetEmail(f.email,link);console.log('Şifre sıfırlama e-postası gönderildi:',f.email)}catch(e){console.error('E-posta gönderilemedi:',e.message);return json(res,500,{error:'E-posta gönderilemedi. SMTP ayarlarını kontrol edin.'})}return json(res,200,generic)}
if(req.method==='POST'&&p==='/api/reset-password'){let i=await body(req),token=clean(i.token,200),pass=String(i.newPassword||'');if(pass.length<8)return json(res,400,{error:'Yeni şifre en az 8 karakter olmalı.'});let c=await pool.connect();try{await c.query('BEGIN');let r=await c.query(`SELECT prt.*,u.email FROM password_reset_tokens prt JOIN users u ON u.id=prt.user_id WHERE prt.token_hash=$1 AND prt.used_at IS NULL AND prt.expires_at>NOW() FOR UPDATE`,[tokenHash(token)]),t=r.rows[0];if(!t){await c.query('ROLLBACK');return json(res,400,{error:'Bağlantı geçersiz veya süresi dolmuş.'})}let salt=crypto.randomBytes(16).toString('hex');await c.query('UPDATE users SET salt=$1,password_hash=$2,updated_at=NOW(),last_password_changed_at=NOW() WHERE id=$3',[salt,hash(pass,salt),t.user_id]);await c.query('UPDATE password_reset_tokens SET used_at=NOW() WHERE id=$1',[t.id]);await c.query('DELETE FROM sessions WHERE user_id=$1',[t.user_id]);await c.query('COMMIT');const when=new Date().toLocaleString('tr-TR',{timeZone:'Europe/Istanbul'});sendPasswordChangedEmail(t.email,when).catch(e=>console.error('Şifre değişikliği e-postası gönderilemedi:',e.message));return json(res,200,{ok:true,message:'Şifreniz yenilendi. Giriş yapabilirsiniz.'})}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}
if(req.method==='POST'&&p==='/api/logout'){let sid=cookies(req).sid;if(sid)await pool.query('DELETE FROM sessions WHERE id=$1',[sid]);return json(res,200,{ok:true},{'Set-Cookie':'sid=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0'})}
if(req.method==='GET'&&p==='/api/manage/streamers'){if(!await auth(req,res,['owner','admin','moderator']))return;let r=await pool.query('SELECT * FROM streamers ORDER BY display_name');return json(res,200,{streamers:r.rows.map(mapStreamer)})}
if(req.method==='POST'&&p==='/api/manage/streamers'){if(!await auth(req,res,['owner','admin']))return;let i=await body(req),name=clean(i.name,100),slug=slugify(i.slug||name);if(!name||!slug)return json(res,400,{error:'Ad ve profil adresi gerekli.'});let r=await pool.query(`INSERT INTO streamers(slug,display_name,kick_username,kick_url,avatar_url,bio,categories,socials,active) VALUES($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9) RETURNING *`,[slug,name,clean(i.kickUsername,100),clean(i.kickUrl,300),clean(i.avatarUrl,500),clean(i.bio,2000),clean(i.categories,300),JSON.stringify(i.socials||{}),i.active!==false]);return json(res,201,mapStreamer(r.rows[0]))}
let sm=p.match(/^\/api\/manage\/streamers\/(\d+)$/);if(sm&&req.method==='PUT'){if(!await auth(req,res,['owner','admin']))return;let i=await body(req),name=clean(i.name,100),slug=slugify(i.slug||name);let r=await pool.query(`UPDATE streamers SET slug=$1,display_name=$2,kick_username=$3,kick_url=$4,avatar_url=$5,bio=$6,categories=$7,socials=$8::jsonb,active=$9,updated_at=NOW() WHERE id=$10 RETURNING *`,[slug,name,clean(i.kickUsername,100),clean(i.kickUrl,300),clean(i.avatarUrl,500),clean(i.bio,2000),clean(i.categories,300),JSON.stringify(i.socials||{}),i.active!==false,Number(sm[1])]);if(!r.rowCount)return json(res,404,{error:'Yayıncı bulunamadı.'});return json(res,200,mapStreamer(r.rows[0]))}
if(sm&&req.method==='DELETE'){if(!await auth(req,res,['owner','admin']))return;await pool.query('DELETE FROM streamers WHERE id=$1',[Number(sm[1])]);return json(res,200,{ok:true})}
if(req.method==='GET'&&p==='/api/manage/users'){if(!await auth(req,res,['owner','admin']))return;let r=await pool.query('SELECT id,username,email,role,streamer_id,active,created_at FROM users ORDER BY username');return json(res,200,{users:r.rows})}
if(req.method==='POST'&&p==='/api/manage/users'){if(!await auth(req,res,['owner','admin']))return;let i=await body(req),username=clean(i.username,60),email=clean(i.email,254).toLowerCase()||null,pass=String(i.password||''),role=['admin','moderator','streamer'].includes(i.role)?i.role:'moderator';if(!username||pass.length<8)return json(res,400,{error:'Kullanıcı adı ve en az 8 karakter şifre gerekli.'});let salt=crypto.randomBytes(16).toString('hex');let r=await pool.query('INSERT INTO users(username,email,salt,password_hash,role,streamer_id,active) VALUES($1,$2,$3,$4,$5,$6,TRUE) RETURNING id,username,email,role,streamer_id,active',[username,email,salt,hash(pass,salt),role,Number(i.streamerId)||null]);return json(res,201,r.rows[0])}
let um=p.match(/^\/api\/manage\/users\/(\d+)$/);if(um&&req.method==='PUT'){if(!await auth(req,res,['owner','admin']))return;let i=await body(req),role=['admin','moderator','streamer'].includes(i.role)?i.role:'moderator';let sets=['role=$1','streamer_id=$2','active=$3','email=$4','updated_at=NOW()'],vals=[role,Number(i.streamerId)||null,i.active!==false,clean(i.email,254).toLowerCase()||null];if(i.password){if(String(i.password).length<8)return json(res,400,{error:'Şifre en az 8 karakter olmalı.'});let salt=crypto.randomBytes(16).toString('hex');sets.push(`salt=$${vals.length+1}`,`password_hash=$${vals.length+2}`);vals.push(salt,hash(String(i.password),salt))}vals.push(Number(um[1]));await pool.query(`UPDATE users SET ${sets.join(',')} WHERE id=$${vals.length}`,vals);return json(res,200,{ok:true})}
if(req.method==='GET'&&p==='/api/reports'){let cu=await auth(req,res,['owner','admin','moderator']);if(!cu)return;let r=await pool.query(`SELECT mr.*,u.username moderator_username,b.title,b.streamer,b.broadcast_date,b.start_time,b.end_time FROM moderator_reports mr JOIN users u ON u.id=mr.moderator_user_id JOIN broadcasts b ON b.id=mr.broadcast_id ORDER BY mr.created_at DESC LIMIT 200`);return json(res,200,{reports:r.rows})}
if(req.method==='POST'&&p==='/api/reports'){let cu=await auth(req,res,['owner','admin','moderator']);if(!cu)return;let i=await body(req),status=['ok','late','absent','technical'].includes(i.attendanceStatus)?i.attendanceStatus:'ok';let r=await pool.query(`INSERT INTO moderator_reports(broadcast_id,moderator_user_id,attendance_status,actual_start,actual_end,technical_issue,note) VALUES($1,$2,$3,$4::time,$5::time,$6,$7) RETURNING *`,[Number(i.broadcastId),cu.id,status,validTime(i.actualStart)?i.actualStart:null,validTime(i.actualEnd)?i.actualEnd:null,clean(i.technicalIssue,1000),clean(i.note,2000)]);return json(res,201,r.rows[0])}
if(req.method==='GET'&&p==='/api/broadcasts'){let cu=await auth(req,res,['owner','admin','moderator','streamer']);if(!cu)return;let r=await pool.query(`${broadcastSelect} ORDER BY b.broadcast_date DESC,b.start_time DESC LIMIT 500`);return json(res,200,{broadcasts:r.rows.map(mapBroadcast)})}
if(req.method==='POST'&&p==='/api/broadcasts'){if(!await auth(req,res,['owner','admin']))return;let i=await body(req),x=broadcastInput(i);if(x.streamerId){let sr=await pool.query('SELECT display_name,kick_url FROM streamers WHERE id=$1',[x.streamerId]);if(sr.rowCount){x.streamer=sr.rows[0].display_name;if(!x.url)x.url=sr.rows[0].kick_url}}if(!x.streamer||!x.title||!validDate(x.date)||!validTime(x.start)||!validTime(x.end)||x.end<=x.start)return json(res,400,{error:'Yayın bilgileri geçersiz.'});let c=await pool.connect();try{await c.query('BEGIN');await c.query('SELECT pg_advisory_xact_lock(hashtext($1))',[x.date]);if(await conflict(c,x)&&!i.force){await c.query('ROLLBACK');return json(res,409,{error:'Bu saat aralığında başka yayın var.'})}let r=await c.query(`INSERT INTO broadcasts(streamer,streamer_id,title,broadcast_date,start_time,end_time,status,url,description) VALUES($1,$2,$3,$4::date,$5::time,$6::time,$7,$8,$9) RETURNING *`,[x.streamer,x.streamerId,x.title,x.date,x.start,x.end,x.status,x.url,x.description]);await c.query('COMMIT');return json(res,201,mapBroadcast(r.rows[0]))}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}
let bm=p.match(/^\/api\/broadcasts\/(\d+)$/);if(bm&&req.method==='PUT'){if(!await auth(req,res,['owner','admin']))return;let i=await body(req),x=broadcastInput(i),id=Number(bm[1]);if(x.streamerId){let sr=await pool.query('SELECT display_name,kick_url FROM streamers WHERE id=$1',[x.streamerId]);if(sr.rowCount){x.streamer=sr.rows[0].display_name;if(!x.url)x.url=sr.rows[0].kick_url}}let c=await pool.connect();try{await c.query('BEGIN');if(await conflict(c,x,id)&&!i.force){await c.query('ROLLBACK');return json(res,409,{error:'Bu saat aralığında başka yayın var.'})}await c.query(`UPDATE broadcasts SET streamer=$1,streamer_id=$2,title=$3,broadcast_date=$4::date,start_time=$5::time,end_time=$6::time,status=$7,url=$8,description=$9,updated_at=NOW() WHERE id=$10`,[x.streamer,x.streamerId,x.title,x.date,x.start,x.end,x.status,x.url,x.description,id]);await c.query('COMMIT');return json(res,200,{ok:true})}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}
if(bm&&req.method==='DELETE'){if(!await auth(req,res,['owner','admin']))return;await pool.query('DELETE FROM broadcasts WHERE id=$1',[Number(bm[1])]);return json(res,200,{ok:true})}

if(req.method==='GET'&&p==='/api/operations'){let cu=await auth(req,res,['owner','admin','moderator','streamer']);if(!cu)return;let today=new Date().toISOString().slice(0,10);let [br,an,sp,nt]=await Promise.all([
pool.query(`${broadcastSelect} WHERE b.broadcast_date BETWEEN CURRENT_DATE-1 AND CURRENT_DATE+7 ORDER BY b.broadcast_date,b.start_time`),
pool.query(`SELECT a.*,u.username created_by_name FROM announcements a LEFT JOIN users u ON u.id=a.created_by WHERE a.active=TRUE ORDER BY CASE a.priority WHEN 'urgent' THEN 0 WHEN 'important' THEN 1 ELSE 2 END,a.created_at DESC LIMIT 20`),
pool.query(`SELECT st.*,s.brand_name,s.campaign_name,b.title broadcast_title,b.broadcast_date,b.start_time,str.display_name streamer_name FROM sponsor_tasks st JOIN sponsors s ON s.id=st.sponsor_id LEFT JOIN broadcasts b ON b.id=st.broadcast_id LEFT JOIN streamers str ON str.id=st.streamer_id WHERE st.status<>'done' ORDER BY st.due_at NULLS LAST,st.created_at DESC LIMIT 100`),
pool.query(`SELECT onote.*,u.username,b.title,b.streamer,b.broadcast_date FROM operation_notes onote LEFT JOIN users u ON u.id=onote.user_id LEFT JOIN broadcasts b ON b.id=onote.broadcast_id ORDER BY onote.created_at DESC LIMIT 50`)]);return json(res,200,{broadcasts:br.rows.map(mapBroadcast),announcements:an.rows,sponsorTasks:sp.rows,notes:nt.rows,today})}
if(req.method==='POST'&&p==='/api/announcements'){let cu=await auth(req,res,['owner','admin']);if(!cu)return;let i=await body(req),title=clean(i.title,140),content=clean(i.content,2500),priority=['normal','important','urgent'].includes(i.priority)?i.priority:'normal';if(!title)return json(res,400,{error:'Duyuru başlığı gerekli.'});let r=await pool.query('INSERT INTO announcements(title,content,priority,active,created_by) VALUES($1,$2,$3,$4,$5) RETURNING *',[title,content,priority,i.active!==false,cu.id]);return json(res,201,r.rows[0])}
if(req.method==='GET'&&p==='/api/sponsors'){if(!await auth(req,res,['owner','admin','moderator']))return;let [s,t]=await Promise.all([pool.query('SELECT * FROM sponsors ORDER BY created_at DESC'),pool.query(`SELECT st.*,s.brand_name,s.campaign_name,b.title broadcast_title,b.broadcast_date,str.display_name streamer_name FROM sponsor_tasks st JOIN sponsors s ON s.id=st.sponsor_id LEFT JOIN broadcasts b ON b.id=st.broadcast_id LEFT JOIN streamers str ON str.id=st.streamer_id ORDER BY st.created_at DESC`)]);return json(res,200,{sponsors:s.rows,tasks:t.rows})}
if(req.method==='POST'&&p==='/api/sponsors'){if(!await auth(req,res,['owner','admin']))return;let i=await body(req),name=clean(i.brandName,140);if(!name)return json(res,400,{error:'Marka adı gerekli.'});let r=await pool.query(`INSERT INTO sponsors(brand_name,campaign_name,logo_url,start_date,end_date,status,brief) VALUES($1,$2,$3,$4::date,$5::date,$6,$7) RETURNING *`,[name,clean(i.campaignName,180),clean(i.logoUrl,500),validDate(i.startDate)?i.startDate:null,validDate(i.endDate)?i.endDate:null,['active','planned','completed','cancelled'].includes(i.status)?i.status:'active',clean(i.brief,3000)]);return json(res,201,r.rows[0])}
if(req.method==='POST'&&p==='/api/sponsor-tasks'){if(!await auth(req,res,['owner','admin']))return;let i=await body(req),title=clean(i.title,180);if(!Number(i.sponsorId)||!title)return json(res,400,{error:'Sponsor ve görev başlığı gerekli.'});let r=await pool.query(`INSERT INTO sponsor_tasks(sponsor_id,broadcast_id,streamer_id,task_type,title,due_at,status,note) VALUES($1,$2,$3,$4,$5,$6::timestamptz,$7,$8) RETURNING *`,[Number(i.sponsorId),Number(i.broadcastId)||null,Number(i.streamerId)||null,clean(i.taskType,60)||'other',title,i.dueAt||null,'pending',clean(i.note,2000)]);return json(res,201,r.rows[0])}
let stm=p.match(/^\/api\/sponsor-tasks\/(\d+)$/);if(stm&&req.method==='PUT'){let cu=await auth(req,res,['owner','admin','moderator','streamer']);if(!cu)return;let i=await body(req),status=['pending','in_progress','submitted','done','rejected'].includes(i.status)?i.status:'pending';await pool.query('UPDATE sponsor_tasks SET status=$1,proof_url=$2,note=$3,updated_at=NOW() WHERE id=$4',[status,clean(i.proofUrl,500),clean(i.note,2000),Number(stm[1])]);return json(res,200,{ok:true})}

if(req.method==='GET'&&p==='/api/sponsor-assistant'){let cu=await auth(req,res,['owner','admin','moderator','streamer']);if(!cu)return;let filter='',vals=[];if(cu.role==='streamer'){if(!cu.streamer_id)return json(res,200,{tasks:[],reminders:[]});filter=' WHERE COALESCE(st.streamer_id,b.streamer_id)=$1';vals=[cu.streamer_id]}let tasks=await pool.query(`SELECT st.id sponsor_task_id,st.title,st.note,st.status task_status,s.brand_name,s.campaign_name,b.id broadcast_id,b.streamer_id,b.streamer,b.title broadcast_title,b.broadcast_date,b.start_time,b.end_time,COALESCE(st.streamer_id,b.streamer_id) assigned_streamer_id FROM sponsor_tasks st JOIN sponsors s ON s.id=st.sponsor_id LEFT JOIN broadcasts b ON b.id=st.broadcast_id${filter} ORDER BY b.broadcast_date DESC,b.start_time DESC`,vals);let rf=cu.role==='streamer'?' WHERE sr.streamer_id=$1':'';let reminders=await pool.query(`SELECT sr.*,st.title,s.brand_name,s.campaign_name,b.streamer,b.title broadcast_title,b.broadcast_date,b.start_time,b.end_time FROM sponsor_reminders sr JOIN sponsor_tasks st ON st.id=sr.sponsor_task_id JOIN sponsors s ON s.id=st.sponsor_id JOIN broadcasts b ON b.id=sr.broadcast_id${rf} ORDER BY sr.remind_at DESC`,cu.role==='streamer'?[cu.streamer_id]:[]);return json(res,200,{tasks:tasks.rows,reminders:reminders.rows})}
if(req.method==='POST'&&p==='/api/sponsor-reminders'){let cu=await auth(req,res,['owner','admin','streamer']);if(!cu)return;let i=await body(req),taskId=Number(i.sponsorTaskId),mode=['after_start','before_end','absolute'].includes(i.timingMode)?i.timingMode:'after_start',offset=Math.max(0,Math.min(600,Number(i.offsetMinutes)||0));let tr=await pool.query(`SELECT st.id,COALESCE(st.streamer_id,b.streamer_id) streamer_id,b.id broadcast_id,b.broadcast_date,b.start_time,b.end_time FROM sponsor_tasks st JOIN broadcasts b ON b.id=st.broadcast_id WHERE st.id=$1`,[taskId]),t=tr.rows[0];if(!t||!t.streamer_id)return json(res,400,{error:'Yayına bağlı geçerli bir sponsor görevi seçin.'});if(cu.role==='streamer'&&Number(cu.streamer_id)!==Number(t.streamer_id))return json(res,403,{error:'Yalnızca kendi yayınınız için hatırlatıcı oluşturabilirsiniz.'});let abs=i.absoluteAt||null;if(mode==='absolute'&&!abs)return json(res,400,{error:'Belirli saat seçildiğinde tarih ve saat gerekli.'});let calc=await pool.query(`SELECT CASE WHEN $1='after_start' THEN (($2::date+$3::time) AT TIME ZONE 'Europe/Istanbul')+($4||' minutes')::interval WHEN $1='before_end' THEN (($2::date+$5::time) AT TIME ZONE 'Europe/Istanbul')-($4||' minutes')::interval ELSE $6::timestamptz END remind_at`,[mode,String(t.broadcast_date).slice(0,10),String(t.start_time).slice(0,5),String(offset),String(t.end_time).slice(0,5),abs]);let checklist=Array.isArray(i.checklist)?i.checklist.map(x=>clean(x,200)).filter(Boolean).slice(0,20):clean(i.checklist,2000).split('\n').map(x=>x.trim()).filter(Boolean).slice(0,20);let r=await pool.query(`INSERT INTO sponsor_reminders(sponsor_task_id,broadcast_id,streamer_id,created_by,timing_mode,offset_minutes,absolute_at,message,promo_code,promo_link,checklist,remind_at) VALUES($1,$2,$3,$4,$5,$6,$7::timestamptz,$8,$9,$10,$11::jsonb,$12) RETURNING *`,[taskId,t.broadcast_id,t.streamer_id,cu.id,mode,offset,abs,clean(i.message,4000),clean(i.promoCode,140),clean(i.promoLink,500),JSON.stringify(checklist),calc.rows[0].remind_at]);return json(res,201,r.rows[0])}
let srm=p.match(/^\/api\/sponsor-reminders\/(\d+)$/);if(srm&&req.method==='PUT'){let cu=await auth(req,res,['owner','admin','moderator','streamer']);if(!cu)return;let id=Number(srm[1]),own=await pool.query('SELECT * FROM sponsor_reminders WHERE id=$1',[id]),r0=own.rows[0];if(!r0)return json(res,404,{error:'Hatırlatıcı bulunamadı.'});if(cu.role==='streamer'&&Number(cu.streamer_id)!==Number(r0.streamer_id))return json(res,403,{error:'Yetkiniz yok.'});let i=await body(req),action=clean(i.action,30);if(action==='seen')await pool.query("UPDATE sponsor_reminders SET status='seen',seen_at=NOW(),updated_at=NOW() WHERE id=$1",[id]);else if(action==='completed')await pool.query("UPDATE sponsor_reminders SET status='completed',completed_at=NOW(),updated_at=NOW() WHERE id=$1",[id]);else if(action==='snooze'){let mins=[5,10,15].includes(Number(i.minutes))?Number(i.minutes):10;await pool.query("UPDATE sponsor_reminders SET status='snoozed',snoozed_until=NOW()+($2||' minutes')::interval,remind_at=NOW()+($2||' minutes')::interval,notified_at=NULL,updated_at=NOW() WHERE id=$1",[id,String(mins)])}else return json(res,400,{error:'Geçersiz işlem.'});return json(res,200,{ok:true})}
if(req.method==='POST'&&p==='/api/operation-notes'){let cu=await auth(req,res,['owner','admin','moderator']);if(!cu)return;let i=await body(req),content=clean(i.content,2500);if(!content)return json(res,400,{error:'Not içeriği gerekli.'});let r=await pool.query('INSERT INTO operation_notes(broadcast_id,user_id,note_type,content) VALUES($1,$2,$3,$4) RETURNING *',[Number(i.broadcastId)||null,cu.id,['note','technical','warning','success'].includes(i.noteType)?i.noteType:'note',content]);return json(res,201,r.rows[0])}


if(req.method==='GET'&&p==='/api/v3/dashboard'){let cu=await auth(req,res,['owner','admin','moderator','streamer']);if(!cu)return;let [stats,tasks,scores,briefings]=await Promise.all([
pool.query(`SELECT (SELECT COUNT(*) FROM broadcasts WHERE broadcast_date=CURRENT_DATE) today_broadcasts,(SELECT COUNT(*) FROM broadcasts WHERE broadcast_date=CURRENT_DATE AND status='live') live_count,(SELECT COUNT(*) FROM streamers WHERE active=TRUE) active_streamers,(SELECT COUNT(*) FROM users WHERE active=TRUE AND role='moderator') moderators,(SELECT COUNT(*) FROM sponsor_tasks WHERE status NOT IN ('done','rejected')) sponsor_pending,(SELECT COUNT(*) FROM daily_tasks WHERE task_date=CURRENT_DATE AND status<>'done') task_pending,(SELECT COALESCE(SUM(EXTRACT(EPOCH FROM (end_time-start_time))/3600),0) FROM broadcasts WHERE broadcast_date>=date_trunc('week',CURRENT_DATE)::date AND broadcast_date<CURRENT_DATE+1 AND status<>'cancelled') week_hours`),
pool.query(`SELECT t.*,u.username assigned_username,s.display_name streamer_name,b.title broadcast_title FROM daily_tasks t LEFT JOIN users u ON u.id=t.assigned_user_id LEFT JOIN streamers s ON s.id=t.assigned_streamer_id LEFT JOIN broadcasts b ON b.id=t.broadcast_id WHERE t.task_date BETWEEN CURRENT_DATE-1 AND CURRENT_DATE+7 ORDER BY t.task_date,CASE t.priority WHEN 'urgent' THEN 0 WHEN 'high' THEN 1 ELSE 2 END,t.created_at DESC`),
pool.query(`SELECT COALESCE(s.display_name,u.username) name,COALESCE(se.streamer_id,u.streamer_id) streamer_id,SUM(se.points)::int points,COUNT(*)::int events FROM score_events se LEFT JOIN users u ON u.id=se.user_id LEFT JOIN streamers s ON s.id=COALESCE(se.streamer_id,u.streamer_id) WHERE se.created_at>=date_trunc('month',CURRENT_DATE) GROUP BY COALESCE(s.display_name,u.username),COALESCE(se.streamer_id,u.streamer_id) ORDER BY points DESC LIMIT 10`),
pool.query(`SELECT bb.*,b.title,b.streamer,b.broadcast_date,b.start_time FROM broadcast_briefings bb JOIN broadcasts b ON b.id=bb.broadcast_id WHERE b.broadcast_date BETWEEN CURRENT_DATE-1 AND CURRENT_DATE+7 ORDER BY b.broadcast_date,b.start_time`)
]);return json(res,200,{stats:stats.rows[0],tasks:tasks.rows,scores:scores.rows,briefings:briefings.rows})}
if(req.method==='POST'&&p==='/api/tasks'){let cu=await auth(req,res,['owner','admin','moderator']);if(!cu)return;let i=await body(req),title=clean(i.title,180);if(!title||!validDate(i.taskDate))return json(res,400,{error:'Görev başlığı ve tarihi gerekli.'});let r=await pool.query(`INSERT INTO daily_tasks(title,description,task_date,assigned_user_id,assigned_streamer_id,broadcast_id,priority,status,created_by) VALUES($1,$2,$3::date,$4,$5,$6,$7,'pending',$8) RETURNING *`,[title,clean(i.description,2500),i.taskDate,Number(i.assignedUserId)||null,Number(i.assignedStreamerId)||null,Number(i.broadcastId)||null,['normal','high','urgent'].includes(i.priority)?i.priority:'normal',cu.id]);return json(res,201,r.rows[0])}
let taskm=p.match(/^\/api\/tasks\/(\d+)$/);if(taskm&&req.method==='PUT'){let cu=await auth(req,res,['owner','admin','moderator','streamer']);if(!cu)return;let i=await body(req),status=['pending','in_progress','done','cancelled'].includes(i.status)?i.status:'pending';await pool.query(`UPDATE daily_tasks SET status=$1,completed_at=CASE WHEN $1='done' THEN NOW() ELSE NULL END,updated_at=NOW() WHERE id=$2`,[status,Number(taskm[1])]);return json(res,200,{ok:true})}
if(req.method==='POST'&&p==='/api/briefings'){let cu=await auth(req,res,['owner','admin','moderator']);if(!cu)return;let i=await body(req),bid=Number(i.broadcastId);if(!bid)return json(res,400,{error:'Yayın seçimi gerekli.'});let r=await pool.query(`INSERT INTO broadcast_briefings(broadcast_id,talking_points,restricted_topics,sponsor_code,important_links,special_notes,updated_by) VALUES($1,$2,$3,$4,$5,$6,$7) ON CONFLICT(broadcast_id) DO UPDATE SET talking_points=EXCLUDED.talking_points,restricted_topics=EXCLUDED.restricted_topics,sponsor_code=EXCLUDED.sponsor_code,important_links=EXCLUDED.important_links,special_notes=EXCLUDED.special_notes,updated_by=EXCLUDED.updated_by,updated_at=NOW() RETURNING *`,[bid,clean(i.talkingPoints,4000),clean(i.restrictedTopics,3000),clean(i.sponsorCode,120),clean(i.importantLinks,2500),clean(i.specialNotes,3000),cu.id]);return json(res,200,r.rows[0])}
if(req.method==='POST'&&p==='/api/scores'){let cu=await auth(req,res,['owner','admin']);if(!cu)return;let i=await body(req),points=Math.max(-100,Math.min(100,Number(i.points)||0)),reason=clean(i.reason,220);if(!points||!reason||(!Number(i.userId)&&!Number(i.streamerId)))return json(res,400,{error:'Kişi, puan ve gerekçe gerekli.'});let r=await pool.query(`INSERT INTO score_events(user_id,streamer_id,broadcast_id,points,reason,created_by) VALUES($1,$2,$3,$4,$5,$6) RETURNING *`,[Number(i.userId)||null,Number(i.streamerId)||null,Number(i.broadcastId)||null,points,reason,cu.id]);return json(res,201,r.rows[0])}

if(req.method==='GET'&&p==='/api/email-status'){let cu=await auth(req,res,['owner','admin']);if(!cu)return;return json(res,200,{configured:!!mailTransport(),host:clean(process.env.SMTP_HOST,200),port:Number(process.env.SMTP_PORT||587),secure:String(process.env.SMTP_SECURE||'false')==='true',from:clean(process.env.EMAIL_FROM||process.env.SMTP_USER,254)})}
if(req.method==='POST'&&p==='/api/test-email'){let cu=await auth(req,res,['owner','admin']);if(!cu)return;let i=await body(req),to=clean(i.email,254)||clean(process.env.ADMIN_EMAIL,254);if(!to||!/^\S+@\S+\.\S+$/.test(to))return json(res,400,{error:'Geçerli bir test e-posta adresi girin.'});try{await sendTestEmail(to);await pool.query('INSERT INTO email_logs(user_id,recipient,email_type,status) VALUES($1,$2,$3,$4)',[cu.id,to,'smtp_test','sent']);return json(res,200,{ok:true,message:'Test e-postası gönderildi.'})}catch(e){await pool.query('INSERT INTO email_logs(user_id,recipient,email_type,status,error_message) VALUES($1,$2,$3,$4,$5)',[cu.id,to,'smtp_test','failed',clean(e.message,1000)]).catch(()=>{});return json(res,500,{error:'Test e-postası gönderilemedi: '+e.message})}}
if(req.method==='POST'&&p==='/api/change-password'){let cu=await auth(req,res);if(!cu)return;let i=await body(req),r=await pool.query('SELECT salt,password_hash,email FROM users WHERE id=$1',[cu.id]),f=r.rows[0];if(!f||hash(String(i.currentPassword||''),f.salt)!==f.password_hash)return json(res,400,{error:'Mevcut şifre yanlış.'});if(String(i.newPassword||'').length<8)return json(res,400,{error:'Yeni şifre en az 8 karakter olmalı.'});let s=crypto.randomBytes(16).toString('hex');await pool.query('UPDATE users SET salt=$1,password_hash=$2,last_password_changed_at=NOW(),updated_at=NOW() WHERE id=$3',[s,hash(String(i.newPassword),s),cu.id]);await pool.query('DELETE FROM sessions WHERE user_id=$1',[cu.id]);const when=new Date().toLocaleString('tr-TR',{timeZone:'Europe/Istanbul'});sendPasswordChangedEmail(f.email,when).catch(e=>console.error('Şifre değişikliği e-postası gönderilemedi:',e.message));return json(res,200,{ok:true,logout:true,message:'Şifreniz değiştirildi. Güvenlik için yeniden giriş yapın.'},{'Set-Cookie':`sid=; HttpOnly; SameSite=Lax; Path=/; Max-Age=0${process.env.NODE_ENV==='production'?'; Secure':''}`})}

if(req.method==='GET'&&p==='/api/account'){let cu=await auth(req,res,['owner','admin','moderator','streamer']);if(!cu)return;let r=await pool.query(`SELECT id,username,email,display_name,bio,avatar_url,cover_url,role,streamer_id,active,theme,accent,density,reduce_motion,font_scale,high_contrast,created_at FROM users WHERE id=$1`,[cu.id]);return json(res,200,{user:r.rows[0]})}
if(req.method==='PUT'&&p==='/api/account/profile'){let cu=await auth(req,res,['owner','admin','moderator','streamer']);if(!cu)return;let i=await body(req),display=clean(i.displayName,120),bio=clean(i.bio,2000),email=clean(i.email,254).toLowerCase();if(email&&!/^\S+@\S+\.\S+$/.test(email))return json(res,400,{error:'Geçerli bir e-posta girin.'});let r=await pool.query(`UPDATE users SET display_name=$1,bio=$2,email=$3,updated_at=NOW() WHERE id=$4 RETURNING id,username,email,display_name,bio,avatar_url,cover_url,role,streamer_id`,[display,bio,email||null,cu.id]);if(cu.streamer_id)await pool.query(`UPDATE streamers SET display_name=COALESCE(NULLIF($1,''),display_name),bio=$2,updated_at=NOW() WHERE id=$3`,[display,bio,cu.streamer_id]);await pool.query(`INSERT INTO activity_logs(user_id,action,entity_type,entity_id,detail) VALUES($1,'profile_updated','user',$1,$2::jsonb)`,[cu.id,JSON.stringify({displayName:display})]);return json(res,200,{user:r.rows[0]})}
if(req.method==='POST'&&p==='/api/account/avatar'){let cu=await auth(req,res,['owner','admin','moderator','streamer']);if(!cu)return;let i=await body(req),data=String(i.dataUrl||'');if(!/^data:image\/(png|jpeg|webp);base64,/i.test(data))return json(res,400,{error:'PNG, JPG veya WebP görsel seçin.'});if(data.length>1400000)return json(res,400,{error:'Görsel çok büyük. En fazla yaklaşık 1 MB yükleyin.'});await pool.query('UPDATE users SET avatar_url=$1,updated_at=NOW() WHERE id=$2',[data,cu.id]);if(cu.streamer_id)await pool.query('UPDATE streamers SET avatar_url=$1,updated_at=NOW() WHERE id=$2',[data,cu.streamer_id]);await pool.query(`INSERT INTO activity_logs(user_id,action,entity_type,entity_id) VALUES($1,'avatar_updated','user',$1)`,[cu.id]);return json(res,200,{ok:true,avatarUrl:data})}
if(req.method==='PUT'&&p==='/api/account/preferences'){let cu=await auth(req,res,['owner','admin','moderator','streamer']);if(!cu)return;let i=await body(req),theme=['midnight','atabari','graphite','ocean','emerald','light','system'].includes(i.theme)?i.theme:'midnight',accent=['red','blue','green','violet','orange'].includes(i.accent)?i.accent:'red',density=['comfortable','compact'].includes(i.density)?i.density:'comfortable',font=['small','normal','large'].includes(i.fontScale)?i.fontScale:'normal';await pool.query(`UPDATE users SET theme=$1,accent=$2,density=$3,reduce_motion=$4,font_scale=$5,high_contrast=$6,updated_at=NOW() WHERE id=$7`,[theme,accent,density,!!i.reduceMotion,font,!!i.highContrast,cu.id]);return json(res,200,{ok:true,preferences:{theme,accent,density,reduceMotion:!!i.reduceMotion,fontScale:font,highContrast:!!i.highContrast}})}
if(req.method==='GET'&&p==='/api/control/users'){let cu=await auth(req,res,['owner']);if(!cu)return;let r=await pool.query(`SELECT id,username,email,display_name,avatar_url,role,streamer_id,active,created_at FROM users ORDER BY created_at DESC`);return json(res,200,{users:r.rows})}
if(req.method==='POST'&&p==='/api/control/users'){let cu=await auth(req,res,['owner']);if(!cu)return;let i=await body(req),username=clean(i.username,60),pass=String(i.password||''),role=['owner','admin','moderator','streamer'].includes(i.role)?i.role:'streamer',email=clean(i.email,254).toLowerCase()||null;if(!username||pass.length<8)return json(res,400,{error:'Kullanıcı adı ve en az 8 karakter şifre gerekli.'});let salt=crypto.randomBytes(16).toString('hex');let r=await pool.query(`INSERT INTO users(username,email,display_name,salt,password_hash,role,streamer_id,active) VALUES($1,$2,$3,$4,$5,$6,$7,TRUE) RETURNING id,username,email,display_name,role,streamer_id,active`,[username,email,clean(i.displayName,120),salt,hash(pass,salt),role,Number(i.streamerId)||null]);await pool.query(`INSERT INTO activity_logs(user_id,action,entity_type,entity_id,detail) VALUES($1,'user_created','user',$2,$3::jsonb)`,[cu.id,r.rows[0].id,JSON.stringify({username,role})]);return json(res,201,r.rows[0])}
let cuv=p.match(/^\/api\/control\/users\/(\d+)$/);if(cuv&&req.method==='PUT'){let cu=await auth(req,res,['owner']);if(!cu)return;let id=Number(cuv[1]),i=await body(req),role=['owner','admin','moderator','streamer'].includes(i.role)?i.role:'streamer';if(id===Number(cu.id)&&i.active===false)return json(res,400,{error:'Kendi hesabınızı pasif yapamazsınız.'});let target=await pool.query('SELECT role FROM users WHERE id=$1',[id]);if(!target.rowCount)return json(res,404,{error:'Kullanıcı bulunamadı.'});if(target.rows[0].role==='owner'&&role!=='owner'){let count=await pool.query("SELECT COUNT(*)::int c FROM users WHERE role='owner' AND active=TRUE");if(count.rows[0].c<=1)return json(res,400,{error:'Son ana adminin rolü değiştirilemez.'})}await pool.query(`UPDATE users SET role=$1,streamer_id=$2,active=$3,updated_at=NOW() WHERE id=$4`,[role,Number(i.streamerId)||null,i.active!==false,id]);await pool.query(`INSERT INTO activity_logs(user_id,action,entity_type,entity_id,detail) VALUES($1,'role_updated','user',$2,$3::jsonb)`,[cu.id,id,JSON.stringify({role,active:i.active!==false})]);return json(res,200,{ok:true})}
if(req.method==='GET'&&p==='/api/activity'){let cu=await auth(req,res,['owner','admin','moderator','streamer']);if(!cu)return;let vals=[],filter='';if(cu.role==='streamer'){filter='WHERE a.user_id=$1';vals=[cu.id]}let r=await pool.query(`SELECT a.*,COALESCE(NULLIF(u.display_name,''),u.username,'Sistem') actor FROM activity_logs a LEFT JOIN users u ON u.id=a.user_id ${filter} ORDER BY a.created_at DESC LIMIT 100`,vals);return json(res,200,{activities:r.rows})}
if(p.startsWith('/api/'))return json(res,404,{error:'Bulunamadı.'});let file;if(mode==='control'&&(p==='/'||p==='/index.html'||['/admin','/admin/','/moderator','/moderator/','/panel','/panel/'].includes(p)))file=path.join(PUB,'panel.html');else if(mode!=='control'&&(p==='/'||p==='/index.html'))file=path.join(PUB,'index.html');else if(mode!=='control'&&(p==='/yayincilar'||p==='/yayincilar/'))file=path.join(PUB,'streamers.html');else if(mode!=='control'&&/^\/yayinci\/[a-z0-9-]+\/?$/.test(p))file=path.join(PUB,'profile.html');else if(p==='/reset-password'||p==='/reset-password/')file=path.join(PUB,'reset-password.html');else file=path.join(PUB,p);if(!file.startsWith(PUB))return json(res,403,{error:'Yasak'});if(!fs.existsSync(file))file=path.join(PUB,'index.html');return serve(res,file)
}catch(e){console.error(e);return json(res,500,{error:'Sunucu hatası.',detail:process.env.NODE_ENV==='production'?undefined:e.message})}});

async function processSponsorReminders(){if(!databaseReady)return;try{let r=await pool.query(`SELECT sr.*,st.title,s.brand_name,u.email FROM sponsor_reminders sr JOIN sponsor_tasks st ON st.id=sr.sponsor_task_id JOIN sponsors s ON s.id=st.sponsor_id LEFT JOIN users u ON u.streamer_id=sr.streamer_id AND u.role='streamer' AND u.active=TRUE WHERE sr.status IN ('pending','snoozed') AND sr.remind_at<=NOW() AND sr.notified_at IS NULL ORDER BY sr.remind_at LIMIT 20`);for(const x of r.rows){try{if(x.email&&mailTransport())await sendSponsorReminderEmail(x.email,x);await pool.query("UPDATE sponsor_reminders SET status='notified',notified_at=NOW(),updated_at=NOW() WHERE id=$1",[x.id])}catch(e){console.error('Sponsor hatırlatma e-postası:',e.message)}}}catch(e){console.error('Sponsor hatırlatıcı işleyici:',e.message)}}
setInterval(processSponsorReminders,60000).unref();
async function init(){let n=0;while(!databaseReady){n++;try{await migrate();databaseReady=true;console.log('PostgreSQL hazır')}catch(e){databaseError=e;console.error('DB denemesi',n,e.message);await new Promise(r=>setTimeout(r,Math.min(30000,n*5000)))}}}server.listen(PORT,'0.0.0.0',()=>{console.log('ATABARI',PORT);init()});
